@Library('k8s-cicd') _

javaAngularPipeline(
  frontendUrl: 'https://github.com/erwanjouan/test-tool-frontend',
  backendUrl:  'https://github.com/erwanjouan/test-tool-backend',
  baseHref:    '/scheduler/',
  imageRepo:   'rone56/scheduler',
  appName:     'scheduler'
)